name: "Release"

on:
  push:
    tags:
      - v*

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  release:
    uses: wasilibs/actions/.github/workflows/release.yaml@eeee5d072ee283c12eb68e2c4969012fae3d6dd0
    secrets: inherit
